/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SSetVis {
        "data": any[];
        "parallelSetsRibbonTension": number;
    }
}
declare global {
    interface HTMLSSetVisElement extends Components.SSetVis, HTMLStencilElement {
    }
    var HTMLSSetVisElement: {
        prototype: HTMLSSetVisElement;
        new (): HTMLSSetVisElement;
    };
    interface HTMLElementTagNameMap {
        "s-set-vis": HTMLSSetVisElement;
    }
}
declare namespace LocalJSX {
    interface SSetVis {
        "data"?: any[];
        "parallelSetsRibbonTension"?: number;
    }
    interface IntrinsicElements {
        "s-set-vis": SSetVis;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s-set-vis": LocalJSX.SSetVis & JSXBase.HTMLAttributes<HTMLSSetVisElement>;
        }
    }
}
